###############################################################################
#                          Generated on forwardforce.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: tuto1-mysql
      working_dir: /application
      volumes:
        - .:/application
#        - /data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=app
        - MYSQL_USER=app
        - MYSQL_PASSWORD=app
      ports:
        - "2064:3306"

    webserver:
      image: nginx:alpine
      container_name: tuto1-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "2060:80"
       - "2061:443"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: tuto1-php-fpm
      working_dir: /application
      environment:
        XDEBUG_CONFIG: "remote_host=docker.for.mac.host.internal"
        PHP_IDE_CONFIG: "serverName=tuto1-Docker"
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      container_name: tuto1-phpmyadmin
      depends_on:
        - mysql
      links:
        - mysql
      ports:
        - "2063:80"
      environment:
        PMA_HOST: mysql
        PMA_PORT: 3306
        PMA_ARBITRARY: 1
        PMA_USER: 'root'
        PMA_PASSWORD: 'root'
        MYSQL_ROOT_PASSWORD: root
      volumes:
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/php.ini
